name: fpformz
description: Functional input validation library based on Fpdart, which is inspired by Formz.
version: 0.1.4
homepage: https://github.com/mysticfall/fpformz

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.10.0
  fpdart: ^1.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
